### ISSUE TITLE
Readme can't work

### ISSUE THREAD

**Issue by Strnadj** [chadrem/workers#3]
Method **process_event** is in parent class without attributes. Always we can override method **perform_handler**, but it's useless, because if we do this, we are able only to use event **perform**... Last thing, if we override **process_event**, we have to write into body shutdown and exception handler. It will be nice to have in default switch clause **perform_handler** call instead of throwing an exception.

I am able to provide PR with previously mentioned behaviour.

**Comment by chadrem** [comment]
@Strnadj I've made some changes based on your feedback:
- README The Workers class advanced example should now work.
- You can now add custom events by overriding ````event_handler(event)```` and calling ````super(event)```` if you want the default handlers to work.
- Any event handler can now stop the event loop by setting ````@run = false````

I believe these changes address all of your feedback.  If not, please let me know.
