### ISSUE TITLE
Need property or method that recive count tasks in @input_queue

### ISSUE THREAD

**Issue by vadimptr** [chadrem/workers#5]
Need add property for pool that count of tasks performed to pool

**Comment by chadrem** [comment]
@vadimptr at this time I don't plan on adding such a method, but you should be able to do it yourself:

Create a new class using inheritance and add any methods you need (untested code):
````ruby
class MyPool < Workers::Pool
  def input_queue_length
    @input_queue.length
  end
end
````

You can then use this custom pool with the the other classes such as `Schedulers`, `Tasks`, etc.
