### ISSUE TITLE
Feature: Add lifecycle hooks for Threads

### ISSUE THREAD

**Issue by thesmart** [chadrem/workers#6]
Similar to `on_exception`, it would be great to have several lifecycle hooks.  For example:

 * `after_start` - called in the Thread, immediately after a Thread is started
 * `before_exit` - called in the Thread, immediately before the Thread exits

This is important because it provides a way that databases can be connected/disconnected and logs can be opened/closed, etc.  I could create one ThreadPool for my web app that handles database connections and log streams -- this would be very nice. 

Maybe this is already easily achieved?

**Comment by chadrem** [comment]
Hi @thesmart,

Thanks for the feedback. Those hooks look like a good idea as they would simplify the syntax.

You can still accomplish what you want using the current code. A simple way using class inheritance should work well. You end up overriding the shutdown_handler and perform_handler methods in a custom worker class. The perform__handler is called every time you ask the worker to do some work. The shutdown_handler is called only once when you want to get rid of the worker. I hope this helps!

```
# Create a custom worker class.
# This class represents a single event driven thread.
class MyWorker < Workers::Worker
  private

  def shutdown_handler(event)
    disconnect_db
    super
  end

  def perform_handler(event)
    connect_db
    super
  end

  def connect_db
    # Open the DB connection if it doesn't exist.
    puts "connect_db() called."
  end

  def disconnect_db
    # Close the DB connection if it exists.
    puts "disconnect_db() called."
  end
end

# Create a pool with 10 custom workers.
exception_handler = proc { |e|
  puts "Don't forget to handle your exceptions..."
  puts "Exception: #{e.class}: #{e.message}\n#{e.backtrace.join("\n")}"
}
pool = Workers::Pool.new(:worker_class => MyWorker, :on_exception => exception_handler)
pool.perform do
  puts "Hello World!"
end
pool.shutdown
```

**Comment by thesmart** [comment]
This is very helpful thanks.  Ended up with something like this for ActiveRecord:

```
  # A worker that manages ActiveRecord pool connections
  class MyWorker < ::Workers::Worker
    private

    def shutdown_handler(event)
      ::ActiveRecord::Base.connection_pool.checkin(@connection) if @connection
      @connection = nil
      super
    end

    def perform_handler(event)
      # Force timezone to be UTC time. Use: Time.zone.new instead of Time.new
      # This was necessary because timezone is stored in a Thread variable
      Time.zone = 'UTC'
      Figma::Services::ActiveRecord.service
      @connection = ::ActiveRecord::Base.connection_pool.checkout
      super
      ::ActiveRecord::Base.connection_pool.checkin(@connection) if @connection
      @connection = nil
    end

  end
```

**Comment by chadrem** [comment]
Cool nice work. That looks like it should work. If you make an updates/changes please update this issue. I imagine it will be helpful to others in the future. Thank you !
